[patch.crates-io]
slint = { git = "https://github.com/jturcotte/slint", branch = "simon/wgpu-underlay-1.14" }
slint-build = { git = "https://github.com/jturcotte/slint", branch = "simon/wgpu-underlay-1.14" }
